<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AnalysesSeeder extends Seeder
{
    public function run(): void
    {
        // VÉRIFICATION : S'assurer que les tables référencées existent
        $examensCount = DB::table('examens')->count();
        $typesCount = DB::table('types')->count();

        if ($examensCount === 0 || $typesCount === 0) {
            $this->command->error('Les tables examens ou types sont vides. Exécutez leurs seeders d\'abord.');
            return;
        }

        $data = [
            [
                'code' => 'NFS',
                'level' => 'PARENT',
                'parent_abr' => null,
                'designation' => 'HEMOGRAMME',
                'description' => 'Devant toute thrombopénie isolée à l\'examen microscopique, la recherche de Plasmodium est faite systématiquement dans une région endémique du paludisme.',
                'prix' => 15000.00,
                'is_bold' => true,
                'examen_id' => 2,
                'type_id' => 1,
                'valeur_ref' => null,
                'unite' => null,
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => null
            ],
            [
                'code' => 'ASAT',
                'level' => 'NORMAL',
                'parent_abr' => null,
                'designation' => 'ASAT',
                'description' => null,
                'prix' => 6750.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 4,
                'valeur_ref' => '1- 40',
                'unite' => 'UI/l',
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => null
            ],
            [
                'code' => 'ALAT',
                'level' => 'NORMAL',
                'parent_abr' => null,
                'designation' => 'ALAT',
                'description' => null,
                'prix' => 6750.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 4,
                'valeur_ref' => '1-45',
                'unite' => 'UI/l',
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => null
            ],
            [
                'code' => 'GGT',
                'level' => 'NORMAL',
                'parent_abr' => null,
                'designation' => 'GGT',
                'description' => null,
                'prix' => 9000.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 4,
                'valeur_ref' => 'H: 10-50       F: 8-35',
                'unite' => 'UI/l',
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => null
            ],
            [
                'code' => 'BILI',
                'level' => 'PARENT',
                'parent_abr' => null,
                'designation' => 'BILIRUBINE',
                'description' => null,
                'prix' => 14000.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 1,
                'valeur_ref' => null,
                'unite' => null,
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => null
            ],
            [
                'code' => 'BT',
                'level' => 'NORMAL',
                'parent_abr' => 'BILI',
                'designation' => 'Bilirubine totale',
                'description' => null,
                'prix' => 7000.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 4,
                'valeur_ref' => '1-18.81',
                'unite' => 'μmol/l',
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => 96
            ],
            [
                'code' => 'BC',
                'level' => 'NORMAL',
                'parent_abr' => 'BILI',
                'designation' => 'Bilirubine conjuguée (directe)',
                'description' => null,
                'prix' => 7000.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 4,
                'valeur_ref' => '1-4.27',
                'unite' => 'μmol/l',
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => 99
            ],
            [
                'code' => 'PAL',
                'level' => 'NORMAL',
                'parent_abr' => null,
                'designation' => 'Phosphatase alcaline',
                'description' => null,
                'prix' => 8000.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 4,
                'valeur_ref' => '26-117',
                'unite' => 'U/l',
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => null
            ],
            [
                'code' => 'PSA total',
                'level' => 'NORMAL',
                'parent_abr' => null,
                'designation' => 'PSA total',
                'description' => 'Le taux de PSA total peut être au dessus de la normale en cas d\'une prostatite, d\'une tumeur bénigne ou maligne de la prostate. Résultat à interpréter avec la clinique.',
                'prix' => 52000.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 4,
                'valeur_ref' => 'n<4',
                'unite' => 'ng/ml',
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => null
            ],
            [
                'code' => 'Fe',
                'level' => 'NORMAL',
                'parent_abr' => null,
                'designation' => 'Fer sérique',
                'description' => null,
                'prix' => 10000.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 4,
                'valeur_ref' => 'H: 10.7-31             F: 9-30',
                'unite' => 'μmol/l',
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => null
            ],
            [
                'code' => 'CHOL',
                'level' => 'PARENT',
                'parent_abr' => null,
                'designation' => 'BILAN LIPIDIQUE',
                'description' => null,
                'prix' => 28000.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 1,
                'valeur_ref' => null,
                'unite' => null,
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => null
            ],
            [
                'code' => 'CholTotal',
                'level' => 'NORMAL',
                'parent_abr' => 'CHOL',
                'designation' => 'Cholestérol Total',
                'description' => null,
                'prix' => 7000.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 4,
                'valeur_ref' => '< 5.18',
                'unite' => 'mmol/L',
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => 97
            ],
            [
                'code' => 'CHOL_HDL',
                'level' => 'NORMAL',
                'parent_abr' => 'CHOL',
                'designation' => 'HDL Cholestérol',
                'description' => null,
                'prix' => 11000.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 4,
                'valeur_ref' => 'H: 0.9-1.4   F: 1.1-1.6',
                'unite' => 'mmol/L',
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => 98
            ],
            [
                'code' => 'COL_LDL',
                'level' => 'NORMAL',
                'parent_abr' => 'CHOL',
                'designation' => 'LDL Cholestérol',
                'description' => null,
                'prix' => 10000.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 4,
                'valeur_ref' => '3.1- 4,4',
                'unite' => 'mmol/l',
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => 99
            ],
            [
                'code' => 'TRIG',
                'level' => 'NORMAL',
                'parent_abr' => null,
                'designation' => 'Triglycéridémie',
                'description' => null,
                'prix' => 7000.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 4,
                'valeur_ref' => '<1.70',
                'unite' => 'mmol/L',
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => 99
            ],
            [
                'code' => 'T4',
                'level' => 'NORMAL',
                'parent_abr' => null,
                'designation' => 'T4 libre',
                'description' => null,
                'prix' => 37500.00,
                'is_bold' => true,
                'examen_id' => 7,
                'type_id' => 4,
                'valeur_ref' => '66 - 181',
                'unite' => 'nmol/l',
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => null
            ],
            [
                'code' => 'IONO',
                'level' => 'PARENT',
                'parent_abr' => null,
                'designation' => 'IONOGRAMME SANGUIN',
                'description' => 'La longue pose de garrot en cas de prélèvement sanguin difficile peut faire augmenter le taux de Potassium au delà de la valeur normale.',
                'prix' => 18000.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 1,
                'valeur_ref' => null,
                'unite' => null,
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => null
            ],
            [
                'code' => 'Na',
                'level' => 'NORMAL',
                'parent_abr' => 'IONO',
                'designation' => 'Sodium',
                'description' => null,
                'prix' => 100.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 4,
                'valeur_ref' => '135 - 148',
                'unite' => 'mmol/l',
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => 99
            ],
            [
                'code' => 'K',
                'level' => 'NORMAL',
                'parent_abr' => 'IONO',
                'designation' => 'Potassium',
                'description' => null,
                'prix' => 0.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 4,
                'valeur_ref' => '3.50-5.30',
                'unite' => 'mmol/l',
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => 99
            ],
            [
                'code' => 'Cl',
                'level' => 'NORMAL',
                'parent_abr' => 'IONO',
                'designation' => 'Chlore',
                'description' => null,
                'prix' => 0.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 4,
                'valeur_ref' => '98-107',
                'unite' => 'mmol/l',
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => 99
            ],
            [
                'code' => 'BU',
                'level' => 'PARENT',
                'parent_abr' => null,
                'designation' => 'BIOCHIMIE URINAIRE',
                'description' => null,
                'prix' => 7000.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 6,
                'valeur_ref' => null,
                'unite' => null,
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => null
            ],
            [
                'code' => 'protéine-bu',
                'level' => 'NORMAL',
                'parent_abr' => 'BU',
                'designation' => 'Protéinurie',
                'description' => null,
                'prix' => 100.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 11,
                'valeur_ref' => null,
                'unite' => null,
                'suffixe' => null,
                'valeurs_predefinies' => json_encode(['Négatif', 'Positif +', 'Positif ++', 'Positif +++']),
                'ordre' => 99
            ],
            [
                'code' => 'Glucose-u',
                'level' => 'NORMAL',
                'parent_abr' => 'BU',
                'designation' => 'Glucose',
                'description' => null,
                'prix' => 100.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 11,
                'valeur_ref' => null,
                'unite' => null,
                'suffixe' => null,
                'valeurs_predefinies' => json_encode(['Négatif', 'Positif +', 'Positif ++', 'Positif +++']),
                'ordre' => 99
            ],
            [
                'code' => 'Acétone',
                'level' => 'NORMAL',
                'parent_abr' => 'BU',
                'designation' => 'Acétone',
                'description' => null,
                'prix' => 100.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 11,
                'valeur_ref' => null,
                'unite' => null,
                'suffixe' => null,
                'valeurs_predefinies' => json_encode(['Négatif', 'Positif +', 'Positif ++', 'Positif +++']),
                'ordre' => 99
            ],
            [
                'code' => 'Nitrites',
                'level' => 'NORMAL',
                'parent_abr' => 'BU',
                'designation' => 'Nitrites',
                'description' => null,
                'prix' => 100.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 11,
                'valeur_ref' => null,
                'unite' => null,
                'suffixe' => null,
                'valeurs_predefinies' => json_encode(['Négatif', 'Positif +', 'Positif ++', 'Positif +++']),
                'ordre' => 99
            ],
            [
                'code' => 'Sang-u',
                'level' => 'NORMAL',
                'parent_abr' => 'BU',
                'designation' => 'Sang',
                'description' => null,
                'prix' => 200.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 11,
                'valeur_ref' => null,
                'unite' => null,
                'suffixe' => null,
                'valeurs_predefinies' => json_encode(['Négatif', 'Positif +', 'Positif ++', 'Positif +++']),
                'ordre' => 99
            ],
            [
                'code' => 'Urobiline',
                'level' => 'NORMAL',
                'parent_abr' => 'BU',
                'designation' => 'Urobiline',
                'description' => null,
                'prix' => 100.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 11,
                'valeur_ref' => null,
                'unite' => null,
                'suffixe' => null,
                'valeurs_predefinies' => json_encode(['Négatif', 'Positif +', 'Positif ++', 'Positif +++']),
                'ordre' => 99
            ],
            [
                'code' => 'Leucocyte-u',
                'level' => 'NORMAL',
                'parent_abr' => 'BU',
                'designation' => 'Leucocyte',
                'description' => null,
                'prix' => 0.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 11,
                'valeur_ref' => null,
                'unite' => null,
                'suffixe' => null,
                'valeurs_predefinies' => json_encode(['Négatif', 'Positif +', 'Positif ++', 'Positif +++']),
                'ordre' => 99
            ],
            [
                'code' => 'HG',
                'level' => 'NORMAL',
                'parent_abr' => 'NFS',
                'designation' => 'Hémoglobine',
                'description' => null,
                'prix' => 0.00,
                'is_bold' => false,
                'examen_id' => 2,
                'type_id' => 4,
                'valeur_ref' => '120 - 160',
                'unite' => 'g/l',
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => 99
            ],
            [
                'code' => 'HEMATOCRITE',
                'level' => 'NORMAL',
                'parent_abr' => 'NFS',
                'designation' => 'Hématocrite',
                'description' => null,
                'prix' => 0.00,
                'is_bold' => false,
                'examen_id' => 2,
                'type_id' => 4,
                'valeur_ref' => '40 - 55',
                'unite' => '%',
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => 99
            ],
            [
                'code' => 'VGM',
                'level' => 'NORMAL',
                'parent_abr' => 'NFS',
                'designation' => 'VGM',
                'description' => null,
                'prix' => 0.00,
                'is_bold' => false,
                'examen_id' => 2,
                'type_id' => 4,
                'valeur_ref' => '80 - 100',
                'unite' => 'μ³',
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => 99
            ],
            [
                'code' => 'GB0',
                'level' => 'CHILD',
                'parent_abr' => null,
                'designation' => 'Globules blancs',
                'description' => null,
                'prix' => 0.00,
                'is_bold' => false,
                'examen_id' => 2,
                'type_id' => 4,
                'valeur_ref' => '4.00-10',
                'unite' => 'G/l',
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => 99
            ],
            [
                'code' => 'TCMH',
                'level' => 'NORMAL',
                'parent_abr' => 'NFS',
                'designation' => 'TCMH',
                'description' => null,
                'prix' => 0.00,
                'is_bold' => false,
                'examen_id' => 2,
                'type_id' => 4,
                'valeur_ref' => '27 - 41',
                'unite' => 'pg',
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => 99
            ],
            [
                'code' => 'FT',
                'level' => 'PARENT',
                'parent_abr' => null,
                'designation' => 'FT',
                'description' => null,
                'prix' => 1000.00,
                'is_bold' => false,
                'examen_id' => 4,
                'type_id' => 1,
                'valeur_ref' => null,
                'unite' => null,
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => 99
            ],
            [
                'code' => 'HB',
                'level' => 'PARENT',
                'parent_abr' => null,
                'designation' => 'HEPATITE  B',
                'description' => 'Technique ELISA',
                'prix' => 0.00,
                'is_bold' => true,
                'examen_id' => 4,
                'type_id' => 6,
                'valeur_ref' => null,
                'unite' => null,
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => null
            ],
            [
                'code' => 'Ag HBs',
                'level' => 'NORMAL',
                'parent_abr' => 'HB',
                'designation' => 'Antigène HBs',
                'description' => null,
                'prix' => 25000.00,
                'is_bold' => false,
                'examen_id' => 4,
                'type_id' => 10,
                'valeur_ref' => null,
                'unite' => null,
                'suffixe' => null,
                'valeurs_predefinies' => json_encode(['Positif', 'Négatif']),
                'ordre' => 99
            ],
            [
                'code' => 'Ag HBe',
                'level' => 'NORMAL',
                'parent_abr' => 'HB',
                'designation' => 'Antigène HBe',
                'description' => null,
                'prix' => 31000.00,
                'is_bold' => false,
                'examen_id' => 4,
                'type_id' => 10,
                'valeur_ref' => null,
                'unite' => null,
                'suffixe' => null,
                'valeurs_predefinies' => json_encode(['Positif', 'Négatif']),
                'ordre' => 99
            ],
            [
                'code' => 'AcAnti-HBc',
                'level' => 'NORMAL',
                'parent_abr' => 'HB',
                'designation' => 'Anticorps anti-HBc',
                'description' => null,
                'prix' => 38000.00,
                'is_bold' => false,
                'examen_id' => 4,
                'type_id' => 10,
                'valeur_ref' => null,
                'unite' => null,
                'suffixe' => null,
                'valeurs_predefinies' => json_encode(['Positif', 'Négatif']),
                'ordre' => 99
            ],
            [
                'code' => 'Ac antiHBe',
                'level' => 'NORMAL',
                'parent_abr' => 'HB',
                'designation' => 'Anticorps anti-HBe',
                'description' => null,
                'prix' => 35000.00,
                'is_bold' => false,
                'examen_id' => 4,
                'type_id' => 10,
                'valeur_ref' => null,
                'unite' => null,
                'suffixe' => null,
                'valeurs_predefinies' => json_encode(['Positif', 'Négatif']),
                'ordre' => 99
            ],
            [
                'code' => 'Ac antiHBs',
                'level' => 'NORMAL',
                'parent_abr' => 'HB',
                'designation' => 'Anticorps anti-HBs',
                'description' => null,
                'prix' => 39000.00,
                'is_bold' => false,
                'examen_id' => 4,
                'type_id' => 10,
                'valeur_ref' => null,
                'unite' => null,
                'suffixe' => null,
                'valeurs_predefinies' => json_encode(['Positif', 'Négatif']),
                'ordre' => 99
            ],
            [
                'code' => 'KAOP',
                'level' => 'PARENT',
                'parent_abr' => null,
                'designation' => 'Recherche des Kystes, Oeufs, Parasites dans les selles',
                'description' => null,
                'prix' => 13500.00,
                'is_bold' => true,
                'examen_id' => 3,
                'type_id' => 1,
                'valeur_ref' => null,
                'unite' => null,
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => 99
            ],
            [
                'code' => 'SKMacroscopique',
                'level' => 'NORMAL',
                'parent_abr' => 'KAOP',
                'designation' => 'Aspect macroscopique',
                'description' => null,
                'prix' => 0.00,
                'is_bold' => true,
                'examen_id' => 3,
                'type_id' => 8,
                'valeur_ref' => null,
                'unite' => null,
                'suffixe' => null,
                'valeurs_predefinies' => json_encode(['Molle', 'Liquide', 'Normal', 'Dur', 'Autre']),
                'ordre' => 99
            ],
            [
                'code' => 'GLY',
                'level' => 'NORMAL',
                'parent_abr' => null,
                'designation' => 'Glycémie',
                'description' => null,
                'prix' => 7000.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 4,
                'valeur_ref' => '3,89 - 6,05',
                'unite' => 'mmol/l',
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => null
            ],
            [
                'code' => 'CREAT',
                'level' => 'NORMAL',
                'parent_abr' => null,
                'designation' => 'Créatininémie',
                'description' => null,
                'prix' => 7000.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 4,
                'valeur_ref' => 'H: 62-123    F: 53-97',
                'unite' => 'μmol/l',
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => 99
            ],
            [
                'code' => 'CA',
                'level' => 'NORMAL',
                'parent_abr' => null,
                'designation' => 'Calcémie',
                'description' => null,
                'prix' => 7000.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 4,
                'valeur_ref' => 'A: 2.1- 2.5    E: 2.1- 2.7    Nné: 1.9- 2.6',
                'unite' => 'mmol/L',
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => null
            ],
            [
                'code' => 'MG',
                'level' => 'NORMAL',
                'parent_abr' => null,
                'designation' => 'Magnésémie',
                'description' => null,
                'prix' => 6000.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 4,
                'valeur_ref' => '0.66-1.07',
                'unite' => 'mmol/l',
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => null
            ],
            [
                'code' => 'URIC',
                'level' => 'NORMAL',
                'parent_abr' => null,
                'designation' => 'Uricémie',
                'description' => null,
                'prix' => 7000.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 4,
                'valeur_ref' => '155-428',
                'unite' => 'μmol/l',
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => null
            ],
            [
                'code' => 'Protidémie',
                'level' => 'NORMAL',
                'parent_abr' => null,
                'designation' => 'Protidémie',
                'description' => null,
                'prix' => 6000.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 4,
                'valeur_ref' => '65-80',
                'unite' => 'g/l',
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => null
            ],
            [
                'code' => 'Alb',
                'level' => 'NORMAL',
                'parent_abr' => null,
                'designation' => 'Albuminémie',
                'description' => null,
                'prix' => 8000.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 4,
                'valeur_ref' => '35-50',
                'unite' => 'g/l',
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => null
            ],
            [
                'code' => 'Urée',
                'level' => 'NORMAL',
                'parent_abr' => null,
                'designation' => 'Azotémie',
                'description' => null,
                'prix' => 7000.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 4,
                'valeur_ref' => 'Adulte : 2.5 - 6.6',
                'unite' => 'mmol/L',
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => null
            ],
            [
                'code' => 'Amylasémie',
                'level' => 'NORMAL',
                'parent_abr' => null,
                'designation' => 'Amylasémie',
                'description' => null,
                'prix' => 18000.00,
                'is_bold' => true,
                'examen_id' => 1,
                'type_id' => 4,
                'valeur_ref' => '22-80',
                'unite' => 'UI/L',
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => null
            ],
            [
                'code' => 'Amyl',
                'level' => 'NORMAL',
                'parent_abr' => null,
                'designation' => 'Amylasurie',
                'description' => null,
                'prix' => 18000.00,
                'is_bold' => false,
                'examen_id' => 1,
                'type_id' => 4,
                'valeur_ref' => 'N<450',
                'unite' => 'U/l',
                'suffixe' => null,
                'valeurs_predefinies' => null,
                'ordre' => null
            ]
        ];

        // Créer un mapping des codes (abréviations) vers les IDs
        $codeToIdMap = [];

        // D'abord, insérer toutes les analyses PARENT
        foreach ($data as $analyse) {
            if ($analyse['level'] === 'PARENT') {
                $id = DB::table('analyses')->insertGetId([
                    'code' => $analyse['code'],
                    'level' => $analyse['level'],
                    'parent_id' => null,
                    'designation' => $analyse['designation'],
                    'description' => $analyse['description'],
                    'prix' => $analyse['prix'],
                    'is_bold' => $analyse['is_bold'],
                    'examen_id' => $analyse['examen_id'],
                    'type_id' => $analyse['type_id'],
                    'valeur_ref' => $analyse['valeur_ref'],
                    'unite' => $analyse['unite'],
                    'suffixe' => $analyse['suffixe'],
                    'valeurs_predefinies' => $analyse['valeurs_predefinies'],
                    'ordre' => $analyse['ordre'],
                    'status' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);

                $codeToIdMap[$analyse['code']] = $id;
            }
        }

        // Ensuite, insérer les analyses CHILD et NORMAL
        foreach ($data as $analyse) {
            if ($analyse['level'] !== 'PARENT') {
                $parentId = null;

                if ($analyse['parent_abr'] && isset($codeToIdMap[$analyse['parent_abr']])) {
                    $parentId = $codeToIdMap[$analyse['parent_abr']];
                }

                DB::table('analyses')->insert([
                    'code' => $analyse['code'],
                    'level' => $analyse['level'],
                    'parent_id' => $parentId,
                    'designation' => $analyse['designation'],
                    'description' => $analyse['description'],
                    'prix' => $analyse['prix'],
                    'is_bold' => $analyse['is_bold'],
                    'examen_id' => $analyse['examen_id'],
                    'type_id' => $analyse['type_id'],
                    'valeur_ref' => $analyse['valeur_ref'],
                    'unite' => $analyse['unite'],
                    'suffixe' => $analyse['suffixe'],
                    'valeurs_predefinies' => $analyse['valeurs_predefinies'],
                    'ordre' => $analyse['ordre'],
                    'status' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }
        }
    }
}